apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-demo-app
  labels:
    app: {{ .Release.Name }}-demo-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-demo-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-demo-app
        version: {{ .Values.image.tag | quote }}
    spec:
      containers:
        - name: demo-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
