apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-demo-app
spec:
  selector:
    app: {{ .Release.Name }}-demo-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
