apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/creid-octopus/iac-octopus
    targetRevision: HEAD
    # ArgoCD watches this directory and creates an Application for each manifest it finds
    path: argocd/argocd/apps/cluster-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      pruneLast: true
