apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-infra
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: creid-aks-meta-nonproduction
            url: https://creid-aks-meta-nonproduction-p3ulikm8.hcp.centralus.azmk8s.io:443
          - cluster: creid-aks-meta-nonprod-c02
            url: https://creid-aks-meta-nonprod-c02-y84e10fw.hcp.centralus.azmk8s.io:443
          - cluster: creid-aks-meta-nonprod-c03
            url: https://creid-aks-meta-nonprod-c03-0kes0hvc.hcp.centralus.azmk8s.io:443
  template:
    metadata:
      name: '{{cluster}}-infra'
    spec:
      project: default
      destination:
        server: '{{url}}'
        namespace: monitoring
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: "70.*"
          helm:
            valueFiles:
              - $values/argocd/cluster-infra/kube-prometheus/values.yaml
        - repoURL: https://github.com/creid-octopus/iac-octopus
          targetRevision: HEAD
          ref: values
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
