apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  project: default
  sources:
    # kube-prometheus-stack chart from the prometheus-community registry
    - repoURL: https://helm.datadoghq.com
      chart: datadog/datadog
      targetRevision: "3.*.*"
      helm:
        valueFiles:
          - $values/argocd/cluster-infra/datadog/values.yaml
    # Values file from this repo
    - repoURL: https://github.com/creid-octopus/iac-octopus
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      pruneLast: true
    syncOptions:
      - CreateNamespace=true
      # Required for kube-prometheus-stack CRDs (ServerSideApply avoids annotation size limits)
      - ServerSideApply=true
