#!/usr/bin/env bash
# update-env.sh — capture current Terraform outputs as static values in .env.local
#
# Run once after 'terraform apply' to set ARGOCD_SERVER for local tools
# (bootstrap.sh, argocd CLI, etc.). Does NOT run terraform on every shell cd.
#
# Usage:
#   ./scripts/update-env.sh
#   direnv reload

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env.local"
TF_DIR="$SCRIPT_DIR/../terraform"

echo ">>> Reading current outputs from Terraform state..."
ARGOCD_IP=$(terraform -chdir="$TF_DIR" output -raw argocd_server_ip)
RESOURCE_GROUP=$(terraform -chdir="$TF_DIR" output -raw resource_group_name)
CLUSTER_NAME=$(terraform -chdir="$TF_DIR" output -raw cluster_name)

cat > "$ENV_FILE" << EOF
# Generated by scripts/update-env.sh — do not edit manually
# Re-run the script after each 'terraform apply' to refresh values
export ARGOCD_SERVER="$ARGOCD_IP"
EOF

echo ">>> Merging AKS credentials into local kubeconfig..."
az aks get-credentials \
  --resource-group "$RESOURCE_GROUP" \
  --name "$CLUSTER_NAME" \
  --context argocd-demo \
  --overwrite-existing

echo ""
echo "✓ Done"
echo "  ARGOCD_SERVER=$ARGOCD_IP"
echo "  kubectl context: argocd-demo"
echo ""
echo "  Run: direnv reload"
echo "  Then: ./scripts/bootstrap.sh"
